trigger:
  branches:
    include:
      - main
      - ci 
      - feature.*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: UseNode@1
  inputs:
    version: '20.9.0'
  displayName: 'Install Node.js'
- script: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
- script: |
    corepack enable
  displayName: Corepack
- script: |
    yarn install
  displayName: Install
- script: |
    yarn build
  displayName: Build
- script: |
    yarn test
  displayName: Test
  env:
    DISPLAY: ':99.0'
